# 인공지능 수학 - 선형대수 (NumPy 실습)
## 행렬과 벡터의 코딩 및 연산

#### Equation
3x +  y + z = 4  
x  - 2y - z = 1  
x  +  y + x = 1  

In [1]:
import numpy as np

In [2]:
# 행렬 코딩 : 왼->오
A = np.array([[3, 1, 1], [1, -2, -1], [1, 1, 1]])

print(A)
print(A.shape, np.shape(A))

[[ 3  1  1]
 [ 1 -2 -1]
 [ 1  1  1]]
(3, 3) (3, 3)


In [3]:
# 벡터 코딩 : 위->아래
b = np.array([4, 1, 2])

print(b)
print(b.shape)

[4 1 2]
(3,)


In [4]:
# 역행렬 구하기
A_inv = np.linalg.inv(A)

print(A_inv)
print(A_inv.shape)

[[ 5.00000000e-01 -7.40148683e-17 -5.00000000e-01]
 [ 1.00000000e+00 -1.00000000e+00 -2.00000000e+00]
 [-1.50000000e+00  1.00000000e+00  3.50000000e+00]]
(3, 3)


In [5]:
# 역행렬을 이용한 선형 시스템 Ax=b의 해 구하기
x = A_inv @ b

print(x)
print(x.shape)

[ 1. -1.  2.]
(3,)


In [6]:
# 결과 검증
# bb = np.matmul(A, x)
bb = A @ x

print(bb)
print(bb.shape)

[4. 1. 2.]
(3,)


In [8]:
# 크기 비교
if np.linalg.norm(b - bb) < 1e-3 :
    print("OK")
else : print("Something Wrong")

OK
