In [1]:
import numpy as np

# Numpy로 선형대수 지식 끼얹기

## A. Basics

### 영벡터 (행렬)
- 원소가 모두 0인 벡터(행렬)
- `np.zeros(dim)`을 통해 생성, dim은 값, 혹은 튜플(,)

In [2]:
np.zeros(3)

array([0., 0., 0.])

In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 일벡터 (행렬)
* 원소가 모두 1인 벡터(행렬)
* `np.ones(dim)`을 통해 생성, dim은 값, 혹은 튜플(,)

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 대각 행렬 (Diagonal Matrix)
* Main Diagonal을 제외한 성분이 0인 행렬
* `np.diag((main_diagonals))`을 통해 생성할 수 있음

In [6]:
np.diag((2, 4))

array([[2, 0],
       [0, 4]])

In [7]:
np.diag((1, 3, 5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

### 항등 행렬 (Identity matrix)
* Main Diagonal == 1인 Diagonal Matrix
* `np.eye(n, (dtype))`을 통해 생성할 수 있음 
* dtype = intm uint, float, complex, ...

In [8]:
np.eye(3)  # Default dtype = float

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [10]:
np.eye(3, dtype=float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 행렬 곱 (Dot Product)
* 행렬간에 정의되는 곱 연산 (Dot Product)
* `np.dot()` 또는 `@` 사용

In [11]:
mat1 = np.array([[1, 4], [2, 3]])
mat2 = np.array([[7, 9], [0, 6]])

In [12]:
mat1.dot(mat2)

array([[ 7, 33],
       [14, 36]])

In [13]:
mat1 @ mat2

array([[ 7, 33],
       [14, 36]])

In [14]:
mat2.dot(mat1)

array([[25, 55],
       [12, 18]])

## B. Furthermore

### 트레이스 (Trace)

* Main Diagonal의 합(Sum)
* `np.trace()`를 사용


In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr.trace()

15

In [17]:
np.eye(2, dtype=int).trace()

2

### 행렬식 (Determinant)

* 행렬을 대표하는 갑들 중 하나
* 선형 변환 과정에서 Vector의 Scaling 과정
* `np.linalg.det()`으로 계산  


* determinant == 0 : Full Rank가 아님  
  -> column들간의 선형 종속 관계가 있음

In [18]:
arr2 = np.array([[2, 3], [1, 6]])
arr2

array([[2, 3],
       [1, 6]])

In [19]:
np.linalg.det(arr2)   ## ad - bc

9.000000000000002

In [20]:
arr3 = np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]])
arr3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [21]:
np.linalg.det(arr3)  ## 1*(5*9 - 6*8) - 4*(2*9 - 3*8) + 7*(2*6 - 5*3)

0.0

### 역행렬 (Inverse Matrix)

* 행렬 A에 대해서 AB = BA = I를 만족하는 행렬 B (B=A^-1)
* `np.lingalg.inv()` 으로 계산

In [22]:
mat = np.array([[1, 4], [2, 3]])
mat

array([[1, 4],
       [2, 3]])

In [23]:
mat_inv = np.linalg.inv(mat)
mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [24]:
mat @ mat_inv

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00]])

In [25]:
mat_inv @ mat

array([[ 1.00000000e+00, -2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00]])

### 고유값과 고유 벡터 (Eigen Value and Eigen Vector)

* 정방행렬(nxn) A에 대해 $Ax = \lambda$를 만족하는 상수 $\lambda$와 이에 대응하는 벡터
* `np.ling.eig()` 으로 계산
* return : eigenvalue, eigenvector  
  - eigenvector의 열(Column)별로 eigenvalue가 대응
  - eigne vector는 normalize 된 값


* 어떠한 선형 변화는 방향이 변하지 않고 같은 Span에 위치해서 크기만 변함  
  -> Span 되는 비율 : 고유값, Span 영역의 벡터 : 고유 벡터  
* determinant를 계산하고 그 이후 과정 쭉쭉...

In [26]:
mat = np.array([[2, 0, -2], [1, 1, -2], [0, 0, 1]])
mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [27]:
eigen_val, eigen_vec = np.linalg.eig(mat)  

In [28]:
eigen_val

array([1., 2., 1.])

In [29]:
eigen_vec

array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]])

#### Validation

In [30]:
mat @ eigen_vec[:, 0] # Ax

array([0., 1., 0.])

In [31]:
eigen_val[0] * eigen_vec[:, 0] # (lambda)x

array([0., 1., 0.])

In [32]:
print(mat @ eigen_vec[:, 1])
print(eigen_val[1] * eigen_vec[:, 1]) # (lambda)x

[1.41421356 1.41421356 0.        ]
[1.41421356 1.41421356 0.        ]
