## 1. Numpy 선언하기

numpy의 Container : numpy.array

### Numpy 가져오기

In [1]:
import numpy as np

### Numpy 선언하기

In [2]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Numpy Arrray의 형태(Shape)

In [4]:
arr.shape

(3,)

In [5]:
arr_2d.shape

(3, 3)

## 2. Numpy 연산

### Vector와 Scalar 사이의 연산

벡터의 각 원소에 대해서 연산을 진행

In [6]:
x = np.array([1, 2, 3])
c = 5

print("더하기 : {}".format(x+c))
print("빼기  : {}".format(x-c))
print("곱하기 : {}".format(x*c))
print("나누기 : {}".format(x/c))

더하기 : [6 7 8]
빼기  : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


### Vector와 Vector 사이의 연산
벡터의 **같은 인덱스**끼리 연산 진행!!

In [7]:
y = np.array([1, 3, 5])
z = np.array([2, 9, 20])

print("더하기 : {}".format(y+z))
print("빼기  : {}".format(y-z))
print("곱하기 : {}".format(y*z))
print("나누기 : {}".format(y/z))

더하기 : [ 3 12 25]
빼기  : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


## 3. Array의 Indexing과 Slicing
### Array의 Indexing

Python의 List와 유사하게 진행 

* w[row, col] 또는 w[row][col]

In [8]:
w = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

w[0][0]

1

In [9]:
# 12를 가지고 오려면?
w[2, 3]

12

### Array의 Slicing

Python의 List와 유사하게 진행 

* [:b] : 맨 처음부터 b까지(~b-1)  
* [a:] : a부터 끝까지  
* [:]  : 처음부터 끝까지  

In [10]:
w = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

## 2, 3, 6, 7을 가지고 오고 싶다면?
w[0:2,1:3]

array([[2, 3],
       [6, 7]])

## 4. Array의 Broadcasting

기본적으로 같은 Type의 data에 대해서만 연산이 적용 가능  
하지만 만약에 피 연산자가 연산 가능하도로고 변환이 가능하다면 연산이 가능하다.  
이를 **Broadcasting**이라고 한다.  

Element-wise하게 연산 가능하도록 형태가 다른 Array를 변형

1. M X N, M X 1   -> M X 1이 M X N으로 (M의 열벡터가 N개 생기는 모양)
2. M X N, 1 X N   -> 1 X N이 M X N으로 (N의 행벡터가 M개 생기는 모양)
3. M X 1, 1 X N   -> 서로 보완 둘이 같은 모양으로 M X N

### 1. M X N, M X 1

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([0, 1, 0])
x = x[:, None]  ## 열벡터로 Transpose

a+x

array([[1, 2, 3],
       [5, 6, 7],
       [7, 8, 9]])

### 2. M X N, 1 X N

In [12]:
y = np.array([0, 1, -1])  ## 기본적으로 행벡터 

a + y

array([[1, 3, 2],
       [4, 6, 5],
       [7, 9, 8]])

### 3. M X 1, 1 X N 

In [13]:
x + y   ## x는 열벡터, y는 행벡터

array([[ 0,  1, -1],
       [ 1,  2,  0],
       [ 0,  1, -1]])