In [1]:
%matplotlib inline


What is PyTorch?
================

Python 기반의 과학 연산 패키지로 다음과 같은 두 집단을 대상으로 합니다:

-  NumPy를 대체하면서 GPU를 이용한 연산이 필요한 경우
-  최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

Getting Started
---------------

Tensor는 NumPy의 ndarray와 유사하며, 추가로 GPU를 사용한 연산 가속도 가능합니다.



In [2]:
from __future__ import print_function
import torch

torch.__version__

'1.9.0+cu102'

초기화되지 않은 5x3 행렬을 생성합니다:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[1.8737e+16, 3.0897e-41, 3.3631e-44],
        [0.0000e+00,        nan, 3.0897e-41],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 5.2896e+15]])


무작위로 초기화된 행렬을 생성합니다:



In [4]:
x = torch.randn(5, 3)   # random + normal_distribution
print(x)
x = torch.rand(5, 3)    # random (0~1)
print(x)

tensor([[-2.6782, -0.5167, -1.5483],
        [-0.8139, -0.1170,  1.2147],
        [ 0.3990, -1.9658,  0.2447],
        [-0.3107, -1.1207, -0.7998],
        [ 0.7152, -0.9918, -1.1539]])
tensor([[0.5796, 0.5702, 0.5492],
        [0.1340, 0.0287, 0.0405],
        [0.1246, 0.2136, 0.1621],
        [0.1370, 0.2503, 0.0521],
        [0.1358, 0.5456, 0.2690]])


dtype이 long이고 0으로 채워진 행렬을 생성합니다:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.ones(5, 3, dtype=torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


데이터로부터 tensor를 직접 생성합니다:



In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


또는 존재하는 tensor를 바탕으로 tensor를 만듭니다. 
이 메소드(method)들은 사용자로부터 제공된 새로운 값이 없는 한, 입력 tensor의 속성들(예. dtype)을 재사용합니다.


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes  # 이미 존재하는 Tensor를 새로운 Tensor로 바꿈
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.7685, -1.4074, -0.2346],
        [-0.4660, -0.1501,  0.5061],
        [-0.9777, -1.0822,  1.5269],
        [ 0.8841, -0.3329,  0.6461],
        [-2.4796, -3.4714, -1.5277]])


행렬의 크기를 구합니다:



In [9]:
print(x.size())   ## 함수
print(x.shape)    ## size()와 같은 결과

torch.Size([5, 3])
torch.Size([5, 3])



덧셈: 문법1

In [10]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[ 0.7685, -1.4074, -0.2346],
        [-0.4660, -0.1501,  0.5061],
        [-0.9777, -1.0822,  1.5269],
        [ 0.8841, -0.3329,  0.6461],
        [-2.4796, -3.4714, -1.5277]])
tensor([[0.5696, 0.0406, 0.7294],
        [0.7165, 0.4696, 0.1565],
        [0.1043, 0.9707, 0.8708],
        [0.8764, 0.3811, 0.6878],
        [0.8825, 0.6563, 0.9978]])
tensor([[ 1.3380, -1.3669,  0.4948],
        [ 0.2505,  0.3195,  0.6626],
        [-0.8734, -0.1116,  2.3976],
        [ 1.7605,  0.0482,  1.3340],
        [-1.5971, -2.8151, -0.5299]])


덧셈: 문법2



In [11]:
print(torch.add(x, y))

tensor([[ 1.3380, -1.3669,  0.4948],
        [ 0.2505,  0.3195,  0.6626],
        [-0.8734, -0.1116,  2.3976],
        [ 1.7605,  0.0482,  1.3340],
        [-1.5971, -2.8151, -0.5299]])


덧셈: 결과 tensor를 인자로 제공


In [12]:
result = torch.empty(5, 3)
print(result)

torch.add(x, y, out=result)
print(result)

tensor([[ 1.8738e+16,  3.0897e-41,  4.9480e-01],
        [ 2.5052e-01,  3.1947e-01,  6.6260e-01],
        [-8.7340e-01, -1.1156e-01,  2.3976e+00],
        [ 1.7605e+00,  4.8231e-02,  1.3340e+00],
        [-1.5971e+00, -2.8151e+00, -5.2986e-01]])
tensor([[ 1.3380, -1.3669,  0.4948],
        [ 0.2505,  0.3195,  0.6626],
        [-0.8734, -0.1116,  2.3976],
        [ 1.7605,  0.0482,  1.3340],
        [-1.5971, -2.8151, -0.5299]])


덧셈: 바꿔치기(In-place) 방식


In [13]:
# adds x to y   (y = y + x)
print(y)
y.add_(x)
print(y)

tensor([[0.5696, 0.0406, 0.7294],
        [0.7165, 0.4696, 0.1565],
        [0.1043, 0.9707, 0.8708],
        [0.8764, 0.3811, 0.6878],
        [0.8825, 0.6563, 0.9978]])
tensor([[ 1.3380, -1.3669,  0.4948],
        [ 0.2505,  0.3195,  0.6626],
        [-0.8734, -0.1116,  2.3976],
        [ 1.7605,  0.0482,  1.3340],
        [-1.5971, -2.8151, -0.5299]])


#### 바꿔치기(In-place) 방식으로 tensor의 값을 변경하는 연산은 _ 를 접미사로 갖습니다.
예: x.copy_(y), x.t_() 는 x 를 변경합니다.

NumPy스러운 인덱싱 표기 방법을 사용할 수도 있습니다!


In [14]:
print(x)
print(x[:, 1])

tensor([[ 0.7685, -1.4074, -0.2346],
        [-0.4660, -0.1501,  0.5061],
        [-0.9777, -1.0822,  1.5269],
        [ 0.8841, -0.3329,  0.6461],
        [-2.4796, -3.4714, -1.5277]])
tensor([-1.4074, -0.1501, -1.0822, -0.3329, -3.4714])


크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 torch.view 를 사용합니다:


In [15]:
x = torch.randn(4, 4)
print(x)

y = x.view(16)     ## 16개의 차원을 가진 벡터의 형태로 쭉 늘리겠다. 쭉 피겠다.
z = y.view(-1, 2)  # the size -1 is inferred from other dimensions   ## y로 펴 있는 벡터를 -1 : 자동으로 남는 것으로 결정, 2 : column의 개수
print(y)
print(z)
print(y.size(), z.size())

tensor([[ 0.2498, -0.1316,  1.4055,  0.2392],
        [ 0.7750,  0.5547,  0.7937,  1.7463],
        [ 1.4802,  1.4177, -1.1218, -1.1751],
        [ 1.2544, -0.8358,  1.2709,  1.3586]])
tensor([ 0.2498, -0.1316,  1.4055,  0.2392,  0.7750,  0.5547,  0.7937,  1.7463,
         1.4802,  1.4177, -1.1218, -1.1751,  1.2544, -0.8358,  1.2709,  1.3586])
tensor([[ 0.2498, -0.1316],
        [ 1.4055,  0.2392],
        [ 0.7750,  0.5547],
        [ 0.7937,  1.7463],
        [ 1.4802,  1.4177],
        [-1.1218, -1.1751],
        [ 1.2544, -0.8358],
        [ 1.2709,  1.3586]])
torch.Size([16]) torch.Size([8, 2])


만약 tensor에 하나의 값만 존재한다면, .item() 을 사용하면 숫자 값을 얻을 수 있습니다.



In [16]:
x = torch.randn(1)
print(x)
print(type(x), type(x.item()))
print(x.item())


tensor([-0.3591])
<class 'torch.Tensor'> <class 'float'>
-0.35909929871559143


**읽을 거리:**


  전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 난수(random number) 등과 같은 100가지 이상의 Tensor 연산은
  `여기 <http://pytorch.org/docs/torch>` 에 설명되어 있습니다.

NumPy 변환(Bridge)
------------

Torch Tensor를 NumPy 배열(array)로 변환하거나, 그 반대로 하는 것은 매우 쉽습니다.

(CPU 상의) Torch Tensor와 NumPy 배열은 저장 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

- Torch Tensor를 NumPy 배열로 변환하기



In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


NumPy 배열의 값이 어떻게 변하는지 확인해보세요.



In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [20]:
temp = a.clone()           # 깊은 복사
temp_numpy = temp.numpy()

a.add_(1)
print(a)
print(temp_numpy)

tensor([3., 3., 3., 3., 3.])
[2. 2. 2. 2. 2.]


 - NumPy 배열을 Torch Tensor로 변환하기  
 
NumPy(np) 배열을 변경하면 Torch Tensor의 값도 자동 변경되는 것을 확인해보세요.



In [21]:
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensor를 제외한 CPU 상의 모든 Tensor는 NumPy로의 변환을 지원하며, (NumPy에서 Tensor로의) 반대 변환도 지원합니다.

CUDA Tensors
------------

.to 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있습니다.



In [22]:
import torch

# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# ``torch.device`` 를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.

x = torch.rand(4,4)
if torch.cuda.is_available():
    device = "cuda:0" # torch.device("cuda:0")          # CUDA 장치 객체(device object)로
    y = torch.ones_like(x, device=device)  # GPU 상에 직접적으로 tensor를 생성하거나
    print(y)


    x = x.to(device)                       # ``.to("cuda")`` 를 사용하면 됩니다.
    z = x + y                              # 자동으로 device(GPU) 장치 객체
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 는 dtype도 함께 변경합니다!

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
tensor([[1.6166, 1.9499, 1.4215, 1.4609],
        [1.6785, 1.5331, 1.1779, 1.9606],
        [1.6980, 1.6352, 1.7256, 1.7153],
        [1.8737, 1.4967, 1.2076, 1.0988]], device='cuda:0')
tensor([[1.6166, 1.9499, 1.4215, 1.4609],
        [1.6785, 1.5331, 1.1779, 1.9606],
        [1.6980, 1.6352, 1.7256, 1.7153],
        [1.8737, 1.4967, 1.2076, 1.0988]], dtype=torch.float64)


In [23]:
x = x.cuda()     ## cpu에 있는 x를 gpu로 옮기기